import { Nunito } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Project Management",
  description: "Generated by van-tuan.nguyen@thyssenkrupp.com",
};

const font = Nunito({
  subsets: ["latin"],
});
const classNames = {
  showSideBar: "flex-none z-30 w-[100px]",
  hideSideBar: "flex-none z-30 w-[100px] hidden",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  );
}
