import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Sidebar from "./components/sidebar/Sidebar";

export const metadata = {
  title: "Project Management",
  description: "Generated by van-tuan.nguyen@thyssenkrupp.com",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex">
			<div className="flex-none w-auto">
			<Sidebar />
			</div>
			<div className="flex-none w-auto">
			{children}
			</div>
		</div>
      </body>
    </html>
  );
}
